#!/bin/sh
set -e
# Absolute path to this script
SCRIPT=$(readlink -f "$0")

cd $(dirname ${SCRIPT})/..
exit 1
#npm install
#exec node node_modules/browser-sync/bin/browser-sync.js  start --server . --port 3005 --files 'assets/*.css,**/*.js,**/*.html' --no-open
