#!/bin/sh
set -e
# Absolute path to this script
SCRIPT=$(readlink -f "$0")

cd $(dirname ${SCRIPT})/..
npm install
exec node node_modules/browser-sync/bin/browser-sync.js  start --server . --port 3000 --files 'assets/*.css,**/*.js,**/*.html' --no-open
